### ISSUE TITLE
Помощь во внедрении

### ISSUE THREAD

**Issue by pavenkostanislav** [splincode/cryptopro-browser-plugin#1]
Доброе время суток, случайно всплыла в поисковике ссылка на ваш проект, пытаюсь получить список установленных сертификатов, вижу у Вас реализован аналогичный пример, можете уточнить что именно требуется для использования 

> PM> $ npm install cryptopro-browser-plugin --save-dev
> $ : The term '$' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> At line:1 char:1
> + $ npm install cryptopro-browser-plugin --save-dev
> + ~
>     + CategoryInfo          : ObjectNotFound: ($:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pavenkostanislav** [comment]
Добавл TS руками, хотелось бы по возможности пример по использованию

**Comment by splincode** [comment]
Здравствуйте, на самом деле это старый репозиторий, текущая реализация должна выглядеть по-другому и реализация уже другая. По хорошему да, я должен добавить здесь документацию, примеры использования и написать тесты к скриптам. Но на это нужно время...

**Comment by pavenkostanislav** [comment]
А где можно получить свежий репозиторий и какой рабочий версия/дата?

**Comment by splincode** [comment]
Ну для этого, мне нужно сначала навести порядок, отрефакторить код, вынести из приватных репозиториев компании что-то для open source, текущего репозитория нет. Но вы можете самостоятельно написать обертки для крипто-про ЭЦП Browser-plugin. На официальном сайте у них есть вся документация (не трудно разобраться и самостоятельно что-то написать) и они охотно отвечают на своем help desk.

**Comment by pavenkostanislav** [comment]
А не затруднит скинуть какую-нибудь одну ссылочку на форум про ts скрипт?

**Comment by splincode** [comment]
Не совсем понял вопрос,реализация сама у компании КриптоПро есть на JavaScript, вы можете скачать их скрипты, а я же просто сделал обертку на TypeScript и выложил сюда старую версию. А причем тут форумы?

**Comment by pavenkostanislav** [comment]
"охотно отвечают на своем help desk."
Я немного неправильно выразился. Форумом Help desk назвал

**Comment by splincode** [comment]
https://support.cryptopro.ru/
тут они ответят на все ваши вопросы, зарегистрируйтесь и задайте им вопрос, они помогают по всем вопросам, особенно с документацией и их скриптами

**Comment by pavenkostanislav** [comment]
Регистрация есть попробую там.

Решаю задачу по получению на ПК сертификатов. Если выложите новую версию или будет возможность помочь кодом на TS буду благодарен.

Спасибо.

**Comment by pavenkostanislav** [comment]
Удалось получить сертификат для Chrome на языке JS. Отдельное спасибо Вам.
Сейчас пытаюсь написать тоже самое на TS имея скаченную cadesplugin_api.js
Возможно Вы можете поделиться опытом как мне подключить JS к моему файлу TS. Использую Angular 2 beta 16
Зареннее спасибо.

**Comment by splincode** [comment]
Если вы используете сборщик, например, webpack. Вы можете напрямую написать в TypeScript файле импорт нужного вам JS-файла, но дело в том, что вам необходимо иметь 2 версии файлов под разные файлы.

Я обновил пару файлов в репозитории:
1) cryptopro.ts - его нужно комплировать в js, он загружает необходимые js-файлы, которые работают c криптопро эцп browser plugin

2) у меня есть исходные (чутка правил) js-файлы, под разные версии браузеров
async-crypto.es6.js - работает в Chrome, Safari
sync-crypto.js - Firefox, IE (Edge не поддерживается компанией криптопро)

3) Я описал пример:
https://github.com/splincode/cryptopro-browser-plugin/blob/master/readme.md

**Comment by pavenkostanislav** [comment]
Доброе время суток. Прежде всего спасибо. написал свой код по примеру - из студии всё запустил, опубликовал на сайт получил ошибку 500:


> 
Необработанное исключение при выполнении текущего веб-запроса.  Информацию о происхождении и месте возникновения исключения можно получить,  используя следующую трассировку стека исключений.


> [FileNotFoundException: Файл 'C:\...\cryptopro.js' не найден.]    System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) +1346    System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +1132    System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) +146    System.IO.File.InternalReadAllBytes(String path, Boolean checkHost) +126    UACWebApp.AppA2.A2StaticFileHandler.ProcessRequest(HttpContext context) +588    System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +798    System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +91
>

**Comment by splincode** [comment]
cryptopro.js написано же не найден, где-то неправильно подключаете

**Comment by pavenkostanislav** [comment]
Нашёл ошибку - он тупо не скопировался при публикации - странно.
В Chrome удалённо запустил, 
в IE >11 ошибки 

> Unhandled Promise rejection: The selector "my-app" did not match any elements ; Zone: angular ; Task: Promise.then ; Value: The selector "my-app" did not match any elements
>    "Unhandled Promise rejection:"
>    "The selector "my-app" did not match any elements"
>    "; Zone:"
>    "angular"
>    "; Task:"
>    "Promise.then"
>    "; Value:"
>    {
>       [functions]: ,
>       __proto__: { },
>       message: "The selector "my-app" did not match any elements",
>       name: "Error",
>       stack: undefined
>    }
> 

> Uncaught (in promise): The selector "my-app" did not match any elements

**Comment by splincode** [comment]
Хм, my-app это как правило кореневой селектор приложения на Angular. 

Убедитесь, что у вас правильно настроена мета-информация компонента
```typescript
@Component({
    selector: "my-app", // <my-app></my-app>
    templateUrl: "./app.component.html",
})
export class AppComponent {
   ....
}
```

**Comment by pavenkostanislav** [comment]
Всё, пофиксил. Спасибо.

**Comment by pavenkostanislav** [comment]
Теперь буду расширять "interface CertList" до олучения: ключей, токенов, сигнатур
