### ISSUE TITLE
Можно, пример подписания?

### ISSUE THREAD

**Issue by pavenkostanislav** [splincode/cryptopro-browser-plugin#4]
Пробую подписать PDF припомощи 
`signature(certificateName, encodeString)`
Получаю исключения:

> "В режиме strict невозможно получить доступ к свойству \"arguments\" функции"

```
    public signature(certificateName, encodeString) {

        return {
            then: (resolve, reject) => {

                if (this.isChromium) {
                    let thenable = window["SignCreate"](certificateName, encodeString);
                    thenable.then((result) => resolve(result), (error) => reject(error));
                } else {
                    try {
                        let result = window["SignCreate"](certificateName, encodeString);
                        if (result === null) reject(result);
                        else resolve(result); // здесь ошибка в resolve и reject тоже
                    } catch (error) {
                        reject(error);
                    }
                }

            }
        };

    }
```

res = "Failed to create signature. Error: Не удается построить цепочку сертификатов для доверенного корневого центра. (-2146762486)"

```
    public signCreated(certSubjectName: string, file: any): void {

        let encodeString: any = Base64.encode(file);

        this.crypto.then(
            () => {
                this.crypto.signature(certSubjectName, encodeString)
                    .then(
                    (res: any) => {
                        let temp = res;
                    }  // здесь ошибка в res
                    , (error) => {
                        console.error(error);
                    });
            } 
            , (error) => {
                console.error(error);
            });
    }
```

Передаю:
certificateName - text = certObj.GetCertString(); text.replace(/^cn=([^;]+);.+/i, '$1');  (sync-crypto.js)
encodeString -  Base64.encode(fileInput.target.files[0]);  (input type="file" accept=".pdf, application/pdf")

Для Chorme ошибка:

> "A certificate chain could not be built to a trusted root authority. (0x800B010A)"
в файле: 
async-crypto.es6.js
В коде:
`let sSignedMessage = yield oSignedData.SignCades(oSigner, CADESCOM_CADES_X_LONG_TYPE_1);`

**Comment by splincode** [comment]
все будет, попробу написать версию новую

**Comment by pavenkostanislav** [comment]
Вообще странно у меня в синхронной и асинхроннной версиях разные подписи получаются.

**Comment by pavenkostanislav** [comment]
Поправил код работы с плагином:

Асинхронная версия:
```
let oStore = yield cadesplugin.CreateObjectAsync("CAPICOM.Store");
yield oStore.Open(CAPICOM_CURRENT_USER_STORE, CAPICOM_MY_STORE,CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED);
                
let CertificatesObj = yield oStore.Certificates;
let oCertificates = yield CertificatesObj.Find(CAPICOM_CERTIFICATE_FIND_SHA1_HASH, thumbprint);
                
let Count = yield oCertificates.Count;
let oCertificate = yield oCertificates.Item(1);
let oSigner = yield cadesplugin.CreateObjectAsync("CAdESCOM.CPSigner");
yield oSigner.propset_Certificate(oCertificate);
yield oSigner.propset_Options(CAPICOM_CERTIFICATE_INCLUDE_WHOLE_CHAIN);
let tspService =  "http://testca.cryptopro.ru/tsp/";
yield oSigner.propset_TSAAddress(tspService);

let oSignedData = yield cadesplugin.CreateObjectAsync("CAdESCOM.CadesSignedData");
yield oSignedData.propset_ContentEncoding(CADESCOM_ENCODE_BASE64);
yield oSignedData.propset_Content(dataToSign);

let sSignedMessage = yield oSignedData.SignCades(oSigner, CADESCOM_CADES_BES);
                
yield oSignedData.VerifyCades(sSignedMessage, CADESCOM_CADES_BES);

yield oStore.Close();
args[2](sSignedMessage);
return true;
```
Синхронная 
```
let oCertificate;
let oSigner;
let oSignedData;
let sSignedMessage;

let oStore = cadesplugin.CreateObject("CAPICOM.Store");
oStore.Open(CAPICOM_CURRENT_USER_STORE, CAPICOM_MY_STORE, CAPICOM_STORE_OPEN_MAXIMUM_ALLOWED);

let oCertificates = oStore.Certificates.Find(CAPICOM_CERTIFICATE_FIND_SHA1_HASH, thumbprint);

if (oCertificates.Count == 0) {
    return "Certificate not found: " + thumbprint;
}

oCertificate = oCertificates.Item(1);
oSigner = cadesplugin.CreateObject("CAdESCOM.CPSigner");
oSigner.Certificate = oCertificate;
oSigner.TSAAddress = "http://testca.cryptopro.ru/tsp/";

oSignedData = cadesplugin.CreateObject("CAdESCOM.CadesSignedData");
oSignedData.ContentEncoding = CADESCOM_BASE64_TO_BINARY;
oSignedData.Content = dataToSign;

try {
    sSignedMessage = oSignedData.SignCades(oSigner, CADESCOM_CADES_BES);
} catch (err) {
    return "Failed to create signature. Error: " + GetErrorMessage(err);
}

try {
    oSignedData.VerifyCades(sSignedMessage, CADESCOM_CADES_BES,);
} catch (err) {
    alert("Failed to verify signature. Error: " + cadesplugin.getLastError(err));
    return false;
}

oStore.Close();
return sSignedMessage;
```

sSignedMessage - в обоих случая разный. В одном 116 кб в другом 1,2 кб

**Comment by splincode** [comment]
Там проблема в одной единственной штуке
CADESCOM_CADES_X_LONG_TYPE_1 = 0x5d; // позволяет одинаковый делать вроде как

http://cpdn.cryptopro.ru/content/cades/namespace_c_ad_e_s_c_o_m_fe49883d8ff77f7edbeeaf0be3d44c0b_1fe49883d8ff77f7edbeeaf0be3d44c0b.html

**Comment by pavenkostanislav** [comment]
Если меняю строчку на 

`let sSignedMessage = yield oSignedData.SignCades(oSigner, CADESCOM_CADES_X_LONG_TYPE_1);`

> Error "A certificate chain could not be built to a trusted root authority. (0x800B010A)"

**Comment by pavenkostanislav** [comment]
Вообще Нашёл какой-то фак:
[Наиболее распространённые ошибки, связанные с применением](https://www.google.ru/url?sa=t&rct=j&q=&esrc=s&source=web&cd=4&cad=rja&uact=8&ved=0ahUKEwj-ktTT3I3WAhWFIJoKHfQjCGoQFgg9MAM&url=http%3A%2F%2Fwww.gkh76.ru%2Ffiles%2Fdocs%2Fhelp%2Freshenie_problem_pri_registratsii.docx&usg=AFQjCNEshZwYKVP1oeEbF_voXpiKewkTUQ)
> 4.	Сообщение портала: «A certificate chain could not be built to a trusted root authority (0x800B010A) »
> 
> Причина: Корневые сертификаты Удостоверяющего Центра (далее – УЦ) установлены неправильно / не установлены.
> Решение: Необходимо установить корневые сертификаты УЦ (информацию о том, как установить корневые сертификаты, и где их взять можно получить в УЦ, который выдал ЭЦП)

Пробовал ставить как предлагают:
[Установка нового сертификата - КОРУС Консалтинг СНГ](https://www.esphere.ru/assets/download/otchetnost/rukovodstvo_ystanovka_sertifikata.pdf)
Не помогло

**Comment by splincode** [comment]
Я выложил тестовую инструкцию для начала, пока сборку проекта не могу опубликовать, ее надо доделывать

https://github.com/splincode/cryptopro-browser-plugin

**Comment by pavenkostanislav** [comment]
Подпись Тестовым КриптоПрошным сертификатом сформировал. Рабочий вариант у меня в репозитории: [pavenkostanislav/GetingCertificatesList](https://github.com/pavenkostanislav/GetingCertificatesList)

Проверку на [КриптоПро DSS](https://dss.cryptopro.ru/Lite/Verify/) проходит, на [Контур.Крипто](https://crypto.kontur.ru/verify
) НЕТ (и это с ихней подписью но (CADES-BES)

Создал сообщение Диадоковцам: [Не проходит проверка подлинности подписи #243](https://github.com/diadoc/diadocapi-docs/issues/243) пока молчат.

Файл с подписями:
[sign.zip](https://github.com/splincode/cryptopro-browser-plugin/files/1299753/sign.zip)
